# Generated by Django 6.0.2 on 2026-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
