# Generated by Django 6.0.2 on 2026-03-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('videocard', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
