# Generated by Django 6.0.2 on 2026-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
